<?php

$title = 'Lista de Hospitais';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('hospital', ['action' => 'add']) ?>">Adicionar Hospital</a>
</p>

<table class="table">
<tr>
    
    <th>Nome</th>
    <th>Endereco</th>
    <th>Bairro</th>
    <th>Cep</th>
    <th>Telefone</th>
    <th>&nbsp;</th>
</tr>

<?php foreach ($hospitais as $hospital) : ?>
    <tr>
        <td><?= $this->escapeHtml($hospital->nome) ?></td>
        <td><?= $this->escapeHtml($hospital->endereco) ?></td>
        <td><?= $this->escapeHtml($hospital->bairro) ?></td>
        <td><?= $this->escapeHtml($hospital->cep) ?></td>
        <td><?= $this->escapeHtml($hospital->telefone) ?></td>
        <td>
            <a href="<?= $this->url('hospital', ['action' => 'edit', 'id' => $hospital->id]) ?>">Edit</a>
            <a href="<?= $this->url('hospital', ['action' => 'delete', 'id' => $hospital->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>